### ISSUE TITLE
Load Balancer AWS 

### ISSUE THREAD

**Issue by Pxeba** [Martlark/flask-ipban#20]
As I use load balancer on my AWS machine all ip's I get are the same. I can get the ip's I want to manage using 

```Python
request.headers.get('x-forwarded-for') "
```
Is there any way to be able to use the library dealing with the ip this way?

**Comment by Martlark** [comment]
Hi Pxeba,  you can use this:

IP Header

When running a flask app in a docker hosted environment (or similar) the IP address will be the virtual adapter IP and won't change for differing requests. Use your proxy server to set the real IP address in a header so that ip-ban can find what it really is. For apache:

RequestHeader set X_TRUE_IP "%{REMOTE_ADDR}s"

ProxyPass / http://localhost:8080/

ProxyPassReverse / http://localhost:8080/

Then when initializing ip_ban set the header name using the parameter ip_header, in this example: ip_header='X_TRUE_IP'.

**Comment by Martlark** [comment]
ip_ban = IpBan(ip_header='x-forwarded-for')
